language: node_js
node_js:
  - node
  - 4
  - 0.12
addons:
  code_climate:
    repo_token: d3494c5bb5f3df7d98635dbc2aa962c7ce5e14c61f574a8c7304dfa9bc8783e4
script: npm run cover
after_success:
  - cat coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - codeclimate-test-reporter < coverage/lcov.info
